name: fshop
description: FShop - A modern shop management Flutter app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  another_flushbar: ^1.12.32
  image_picker: ^1.2.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  uuid: ^4.5.1
  pdf: ^3.10.7
  path_provider: ^2.1.2
  path: ^1.9.0
  share_plus: ^7.2.2
  url_launcher: ^6.2.2
  qr_flutter: ^4.1.0
  package_info_plus: ^8.0.0
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/sounds/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#9c27b0"
    theme_color: "#9c27b0"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"
